DROP TABLE IF EXISTS ODONTOLOGO;
CREATE TABLE ODONTOLOGO (ID LONG AUTO_INCREMENT PRIMARY KEY,
NUMERO_MATRICULA INT,
NOMBRE VARCHAR(100),
APELLIDO VARCHAR(100));

-- DATOS PARA TEST
INSERT INTO ODONTOLOGO(NUMERO_MATRICULA, NOMBRE, APELLIDO) VALUES (123,'HORACIO','SOSA');
INSERT INTO ODONTOLOGO(NUMERO_MATRICULA, NOMBRE, APELLIDO) VALUES (456,'LISSETTE','QUEBRADA');
